export { default as AppLayout } from './AppLayout.vue'
export { default as AuthLayout } from './AuthLayout.vue'
export { default as LayoutBasic } from './LayoutBasic.vue'
export { default as LayoutTabs } from './LayoutTabs.vue'
export { default as AppLayoutEmployee } from './AppLayoutEmployee.vue'